all : filo_receiver.exe filo_sender.exe
filo_receiver.exe: filo_receiver.c
	gcc filo_receiver.c -o filo_receiver.exe
      
filo_sender.exe: filo_sender.c
	gcc filo_sender.c -o filo_sender.exe
      
      
clean: 
	rm -f filo_sender.exe filo_receiver.exe
